use_frameworks!

target 'XHWaterfallFlowLayout_Example' do
  pod 'XHWaterfallFlowLayout', :path => '../'

  target 'XHWaterfallFlowLayout_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
